name: Continuous Deployment

on:
  release:
    types: [published]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ["lts/Hydrogen"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Install dependencies, build
        run: |
          yarn install
          yarn build
          yarn deploy
